config/routes.rb
Rails.application.routes.draw do
  resources :users do
    post :import, on: :collection
    # import_users     POST   /users/import(.:format)        users#import
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # require 'roo'
  # 有在Gemfile裡寫這個套件，所以不用另外require，跑rails s就會自動require

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "成功創建使用者資料" }
        # url vs path：url所產生的網址會加上域名（http://localhost:3000/）
        # notcie、success、error都可以跳提示
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "成功更新使用者資料" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    # puts params
    excel = Roo::Spreadsheet.open(params[:excel_file].path)

    excel.each_row_streaming(offset: 1) do |row| # 去掉表頭(第一列)
      user = User.new
      # row[0] && row[0].value
      user.name = row[0]&.value # 將excel檔案的第一「欄」資料的值存進user實體中的name欄位 # & 用來確保欄位有值
      user.age = row[1]&.value
      user.save # 存入資料庫
    end

    flash[:success] = "資料已儲存完成"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>姓名:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>年齡:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>頭貼:</strong>
    <%= image_tag user.avatar if user.avatar.attached? %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>使用者列表</h1>


<p>
  <strong>以檔案整批匯入使用者資料:</strong>
</p>

<%= form_with url: import_users_path, method: :post do |form| %>
  <%= form.file_field :excel_file %>
  <%= form.submit %>
<% end %>
<!-- 
<form enctype="multipart/form-data" action="/users" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="g_fHSqRucPyLUZPBCsbeIXwJgrkXYazfyihAbz2-8z0dIummpvUhY3h5q-CY2RcjERk_swahreCb7KTJQv0KBw" autocomplete="off" />
  <input type="file" name="excel_file" id="excel_file" />
</form> -->

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <!-- <%= render partial: "users/user", locals: { user: user } %> -->
    <!-- 第一個user是局部渲染檔案中的區域變數名稱，第二個user是此迴圈中傳入的個別實體變數@user -->
    <p>
      <%= link_to "詳細資訊", user %>
      <!-- <%= link_to "詳細資訊", user_path(user) %> -->
      <!-- <%= link_to "詳細資訊", user_path(user.id) %> -->
    </p>
  <% end %>
</div>

<%= link_to "新建使用者", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "編輯使用者", edit_user_path(@user) %> |
  <%= link_to "返回使用者列表", users_path %>

  <%= button_to "刪除使用者", @user, method: :delete %>
</div>